import {
  ArchitectureGroupAWSCloudlogo,
  ArchitectureServiceAmazonAPIGateway,
  ArchitectureServiceAmazonAthena,
  ArchitectureServiceAmazonCloudFront,
  ArchitectureServiceAmazonDataFirehose,
  ArchitectureServiceAmazonDynamoDB,
  ArchitectureServiceAmazonEC2,
  ArchitectureServiceAmazonElasticContainerService,
  ArchitectureServiceAmazonRDS,
  ArchitectureServiceAmazonSimpleStorageService,
  ArchitectureServiceAWSCloudFormation,
  ArchitectureServiceAWSGlue,
  ArchitectureServiceAWSLambda,
  ArchitectureServiceAmazonSimpleQueueService,
  ArchitectureServiceAWSCloudDevelopmentKit,
  ArchitectureServiceAmazonEC2AutoScaling,
  ArchitectureServiceAmazonElasticContainerRegistry,
  ResourceElasticLoadBalancingNetworkLoadBalancer,
} from 'aws-react-icons'
import { BsBroadcast, BsDiagram3 } from 'react-icons/bs'
import { BiMessageSquareEdit, BiNetworkChart } from 'react-icons/bi'
import { FaAws, FaPhoneAlt, FaProjectDiagram, FaKey } from 'react-icons/fa'
import { FiLink2, FiTerminal, FiActivity } from 'react-icons/fi'
import {
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiGit,
  SiGithubactions,
  SiGraphql,
  SiJavascript,
  SiJest,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNginx,
  SiNodedotjs,
  SiOpenai,
  SiPostgresql,
  SiPython,
  SiRedis,
  SiSocketdotio,
  SiTerraform,
  SiTypescript,
  SiJenkins,
  SiNestjs,
  SiPrometheus,
  SiGrafana,
  SiPostman,
  SiSwagger,
  SiN8N,
  SiSap,
  SiStripe,
  SiPandas,
  SiServerless,
  SiJsonwebtokens,
} from 'react-icons/si'
import { TbApi, TbGitMerge, TbBrandAzure, TbHttpTrace, TbPlugConnected } from 'react-icons/tb'
import { VscCode } from 'react-icons/vsc'

const ICON_MAP = {
  aws: FaAws,
  'aws-apigateway': ArchitectureServiceAmazonAPIGateway,
  'aws-asg': ArchitectureServiceAmazonEC2AutoScaling,
  'aws-athena': ArchitectureServiceAmazonAthena,
  'aws-cdk': ArchitectureServiceAWSCloudDevelopmentKit,
  'aws-cloudformation': ArchitectureServiceAWSCloudFormation,
  'aws-cloudfront': ArchitectureServiceAmazonCloudFront,
  'aws-dynamodb': ArchitectureServiceAmazonDynamoDB,
  'aws-ec2': ArchitectureServiceAmazonEC2,
  'aws-ecr': ArchitectureServiceAmazonElasticContainerRegistry,
  'aws-ecs': ArchitectureServiceAmazonElasticContainerService,
  'aws-firehose': ArchitectureServiceAmazonDataFirehose,
  'aws-glue': ArchitectureServiceAWSGlue,
  'aws-lambda': ArchitectureServiceAWSLambda,
  'aws-nlb': ResourceElasticLoadBalancingNetworkLoadBalancer,
  'aws-rds': ArchitectureServiceAmazonRDS,
  'aws-s3': ArchitectureServiceAmazonSimpleStorageService,
  'aws-sqs': ArchitectureServiceAmazonSimpleQueueService,
  'ai-editors': VscCode,
  'azure-ai': TbBrandAzure,
  bash: FiTerminal,
  cicd: TbGitMerge,
  django: SiDjango,
  'distributed-systems': FaProjectDiagram,
  docker: SiDocker,
  'event-driven': BiNetworkChart,
  express: SiExpress,
  fastapi: SiFastapi,
  git: SiGit,
  githubactions: SiGithubactions,
  grafana: SiGrafana,
  graphql: SiGraphql,
  javascript: SiJavascript,
  jest: SiJest,
  jenkins: SiJenkins,
  'jwe-jws': SiJsonwebtokens,
  langchain: FiLink2,
  linux: SiLinux,
  mcp: TbPlugConnected,
  mongodb: SiMongodb,
  mysql: SiMysql,
  n8n: SiN8N,
  nestjs: SiNestjs,
  nginx: SiNginx,
  nodejs: SiNodedotjs,
  openai: SiOpenai,
  pandas: SiPandas,
  postgresql: SiPostgresql,
  postman: SiPostman,
  prometheus: SiPrometheus,
  prompt: BiMessageSquareEdit,
  python: SiPython,
  rag: BiNetworkChart,
  redis: SiRedis,
  rest: TbApi,
  'sap-btp': SiSap,
  serverless: SiServerless,
  socketio: SiSocketdotio,
  'sso-oauth': FaKey,
  stripe: SiStripe,
  swagger: SiSwagger,
  telnyx: FaPhoneAlt,
  tempo: TbHttpTrace,
  terraform: SiTerraform,
  typescript: SiTypescript,
  websockets: BsBroadcast,
}

const LABEL_ICON_MAP = {
  ai: 'openai',
  'ai editors': 'ai-editors',
  'ai editors (kiro, cursor)': 'ai-editors',
  'api gateway': 'aws-apigateway',
  asg: 'aws-asg',
  athena: 'aws-athena',
  aws: 'aws',
  'aws asg': 'aws-asg',
  'aws bedrock': 'aws',
  'aws cdk': 'aws-cdk',
  'aws ecr': 'aws-ecr',
  'aws glue': 'aws-glue',
  'aws lambda': 'aws-lambda',
  'aws nlb': 'aws-nlb',
  'aws s3': 'aws-s3',
  'aws sqs': 'aws-sqs',
  'azure ai': 'azure-ai',
  'azure ai apis': 'azure-ai',
  azure: 'azure-ai',
  bash: 'bash',
  cdk: 'aws-cdk',
  'ci/cd': 'cicd',
  'ci/cd pipelines': 'cicd',
  cli: 'bash',
  'cloud formation': 'aws-cloudformation',
  cloudformation: 'aws-cloudformation',
  cloudfront: 'aws-cloudfront',
  django: 'django',
  'distributed systems': 'distributed-systems',
  docker: 'docker',
  dynamodb: 'aws-dynamodb',
  ec2: 'aws-ec2',
  ecr: 'aws-ecr',
  'ecs / fargate': 'aws-ecs',
  ecs: 'aws-ecs',
  'event-driven systems': 'event-driven',
  express: 'express',
  'express.js': 'express',
  fargate: 'aws-ecs',
  fastapi: 'fastapi',
  firehose: 'aws-firehose',
  git: 'git',
  'github actions': 'githubactions',
  glue: 'aws-glue',
  grafana: 'grafana',
  graphql: 'graphql',
  javascript: 'javascript',
  jest: 'jest',
  'jwe/jws': 'jwe-jws',
  'jwe/jws security': 'jwe-jws',
  'kinesis firehose': 'aws-firehose',
  lambda: 'aws-lambda',
  langchain: 'langchain',
  linux: 'linux',
  mcp: 'mcp',
  'mcp tooling': 'mcp',
  mongodb: 'mongodb',
  mysql: 'mysql',
  n8n: 'n8n',
  nestjs: 'nestjs',
  nginx: 'nginx',
  nlb: 'aws-nlb',
  'node.js': 'nodejs',
  'openai api': 'openai',
  pandas: 'pandas',
  postgresql: 'postgresql',
  postman: 'postman',
  prometheus: 'prometheus',
  'prompt engineering': 'prompt',
  python: 'python',
  'rag pipelines': 'rag',
  rds: 'aws-rds',
  redis: 'redis',
  rest: 'rest',
  'rest api': 'rest',
  'rest api design': 'rest',
  s3: 'aws-s3',
  sap: 'sap-btp',
  'sap btp': 'sap-btp',
  serverless: 'serverless',
  'socket.io': 'socketio',
  sqs: 'aws-sqs',
  'sso / oauth': 'sso-oauth',
  stripe: 'stripe',
  swagger: 'swagger',
  telnyx: 'telnyx',
  tempo: 'tempo',
  'tempo (tracing)': 'tempo',
  terraform: 'terraform',
  typescript: 'typescript',
  websockets: 'websockets',
  jenkins: 'jenkins',
}

export function getTechIcon(iconKey) {
  return iconKey ? ICON_MAP[iconKey] ?? null : null
}

export function resolveTechIconKey(item) {
  if (item && typeof item === 'object' && item.icon) {
    return item.icon
  }

  const label = typeof item === 'string' ? item : item?.label
  if (!label) {
    return null
  }

  return LABEL_ICON_MAP[label.trim().toLowerCase()] ?? null
}

export function getTechLabel(item) {
  return typeof item === 'string' ? item : item?.label ?? ''
}